# Generated by Django 4.2.2 on 2023-06-21 11:07

import core.post.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_post", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.post.models.post_directory_path
            ),
        ),
    ]
